CREATE TABLE IF NOT EXISTS staging (
  ID SERIAL PRIMARY KEY
, LOAD_ID UUID
, LOAD_TIME TIMESTAMP WITH TIME ZONE
, REPORT_DATE  TIMESTAMP WITH TIME ZONE
, SHERIFF VARCHAR(128)
, COUNT_POPULATION_TOTAL INTEGER
, COUNT_POPULATION_TOTAL_MEN INTEGER
, COUNT_POPULATION_TOTAL_WOMEN INTEGER
, COUNT_POPULATION_SENTENCED_FELONY_MEN INTEGER
, COUNT_POPULATION_SENTENCED_FELONY_WOMEN INTEGER
, COUNT_POPULATION_SENTENCED_MISDEMEANOR_MEN INTEGER
, COUNT_POPULATION_SENTENCED_MISDEMEANOR_WOMEN INTEGER
, COUNT_POPULATION_UNSENTENCED_FELONY_MEN INTEGER
, COUNT_POPULATION_UNSENTENCED_FELONY_WOMEN INTEGER
, COUNT_POPULATION_UNSENTENCED_MISDEMEANOR_MEN INTEGER
, COUNT_POPULATION_UNSENTENCED_MISDEMEANOR_WOMEN INTEGER
)
;
CREATE INDEX IF NOT EXISTS idx_staging 
  ON staging (LOAD_TIME)
;